import rtconfig
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')
group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

objs = objs + group

Return('objs')
